var imagenMujer = document.getElementById("ImagenMujer");
imagenMujer.addEventListener("mouseover", function() {
  imagenMujer.style.opacity = "0.5";
});
imagenMujer.addEventListener("mouseout", function() {
  imagenMujer.style.opacity = "1";
});

var imagenHombre = document.getElementById("ImagenHombre");
imagenHombre.addEventListener("mouseover", function() {
  imagenHombre.style.opacity = "0.5";
});
imagenHombre.addEventListener("mouseout", function() {
  imagenHombre.style.opacity = "1";
});

var imagenJuan = document.getElementById("ImagenJuan");
imagenJuan.addEventListener("mouseover", function() {
  imagenJuan.style.opacity = "0.5";
});
imagenJuan.addEventListener("mouseout", function() {
  imagenJuan.style.opacity = "1";
});